### ISSUE TITLE
如果我添加 listview 头部  会奔溃 

### ISSUE THREAD

**Issue by anjiao** [waynell/VideoListPlayer#14]
java.lang.IndexOutOfBoundsException: Invalid index 5, size is 5
                                                       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                       at java.util.ArrayList.get(ArrayList.java:308)
                                                       at com.volokh.danylo.visibility_utils.calculator.SingleListViewItemActiveCalculator.topToBottomMostVisibleItem(SingleListViewItemActiveCalculator.java:206)
                                                       at com.volokh.danylo.visibility_utils.calculator.SingleListViewItemActiveCalculator.calculateMostVisibleItem(SingleListViewItemActiveCalculator.java:179)
                                                       at com.volokh.danylo.visibility_utils.calculator.SingleListViewItemActiveCalculator.onScrollStateIdle(SingleListViewItemActiveCalculator.java:159)

**Comment by waynell** [comment]
能详细描述下你的问题吗？代码是怎么写的？

**Comment by 88567free** [comment]
就是 listview多加了header头 .addHeader

**Comment by waynell** [comment]
已经更新在ListView中使用示例，并添加了header，但是并没有发生crash。请参考下demo示例中的写法
