### ISSUE TITLE
NullPointerException onScroll

### ISSUE THREAD

**Issue by Prosanto** [waynell/VideoListPlayer#9]
FATAL EXCEPTION: main
                                                              Process: com.gocktrip, PID: 12504
                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
                                                                  at com.waynell.videolist.visibility.items.ListItemData.getIndex(ListItemData.java:17)
                                                                  at com.waynell.videolist.visibility.calculator.SingleListViewItemActiveCalculator.findPreviousItem(SingleListViewItemActiveCalculator.java:132)
                                                                  at com.waynell.videolist.visibility.calculator.SingleListViewItemActiveCalculator.calculateActiveItem(SingleListViewItemActiveCalculator.java:301)
                                                                  at com.waynell.videolist.visibility.calculator.SingleListViewItemActiveCalculator.onStateTouchScroll(SingleListViewItemActiveCalculator.java:75)
                                                                  at com.waynell.videolist.visibility.calculator.BaseItemsVisibilityCalculator.onScrolled(BaseItemsVisibilityCalculator.java:43)
                                                                  at com.gocktrip.videolist.VideoList$1.onScrolled(VideoList.java:129)

**Comment by waynell** [comment]
It has been fixed in latest version
